Login feature is add it all works
AsherBolleddu/CS4389-Chat-Project pull request #8
Opened 2024-10-17 16:17 UTC by soultef

I resolved the conflict and It work in my end.

2024-10-17 18:58 UTC, pmaxhogan requested changes

2024-10-17 18:58 UTC, pmaxhogan commented on src/client.c
> +    unsigned char key[32] = "01234567890123456789012345678901";  // Example 32-byte AES key
These are available in main & should not be hardcoded

2024-10-17 18:58 UTC, pmaxhogan commented on src/server.c
> +        sprintf(hex_password + (i * 2), "%02x", cipherpassword[i]);
How do we know that `hex_password + (i * 2)` is within the bounds of `hex_password`?

2024-10-17 18:58 UTC, pmaxhogan commented on src/server.c
> +          close(client_socket);
Should `fail_client_with_error` instead of the printf & close.

2024-10-17 18:58 UTC, pmaxhogan commented on src/server.c
> +       else{
No need for else if you use `fail_client_with_error` (exits thread)

2024-10-17 18:58 UTC, pmaxhogan commented on src/server.c
> +int check_credentials(const char *username, const unsigned char *cipherpassword) {
Shouldn't the password be decrypted with the IV & key we sent the client? If not then why are we sending those?

2024-10-17 21:46 UTC, JohnPerez15 commented on src/server.c
> +int check_credentials(const char *username, const unsigned char *cipherpassword) {
The IV and Key sent by the server are specific to the serverID's which function as chat rooms. If we use these for the log in we would need 4 different cipher-passwords for each user. I think it is best if we use a different IV and Key for the login authentication check.

2024-10-17 21:52 UTC, soultef commented on src/client.c
> +    unsigned char key[32] = "01234567890123456789012345678901";  // Example 32-byte AES key
It should be hard coded because we cannot have 4 different password.

2024-10-17 22:00 UTC, soultef commented on src/server.c
> +int check_credentials(const char *username, const unsigned char *cipherpassword) {
the password  should not be decrypted with the IV & key  on the server side. Because the server compare the cypher password with the existing Cyphered stored password for the security reasons.

2024-10-17 22:23 UTC, pmaxhogan commented on src/client.c
> +int user_login(int sock)
should be `void` return type

2024-10-17 22:25 UTC, pmaxhogan commented on src/client.c
> +    char buffers[BUFFER_SIZE];
unused

2024-10-22 14:55 UTC, JohnPerez15 commented on src/server.c
> +          close(client_socket);
Th is not cutting connection. Error message when password is wrong. Socket will remain open.

2024-10-23 16:44 UTC, pmaxhogan commented on src/server.c
> +          close(client_socket);
`close(client_socket);` closes the socket

2024-10-27 21:35 UTC, JohnPerez15 commented on src/client.c
> +int user_login(int sock)
changed it.

2024-10-27 21:38 UTC, JohnPerez15 commented on src/client.c
> +    char buffers[BUFFER_SIZE];
Removed

2024-10-27 22:16 UTC, JohnPerez15 commented on src/server.c
> +       else{
changed

2024-10-27 22:16 UTC, JohnPerez15 commented on src/server.c
> +          close(client_socket);
changed

2024-10-27 22:42 UTC, closed without merging